import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

type Token = { $type: string; $value: unknown; $description?: string };
const ROOT = new URL('../', import.meta.url);
const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/[._]/g, '-').toLowerCase();

/** Deliberately bounded DTCG subset; every emitted value is safe inside CSS and HTML. */
export function compileTokens(input: unknown): { values: Record<string, string>; css: string; palettes: Record<string, Record<string, string>>; brand: Record<string, string> } {
  const tokens = new Map<string, Token>(), names = new Set<string>();
  function walk(value: unknown, path: string[] = []): void {
    if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`Invalid token group ${path.join('.')}`);
    const record = value as Record<string, unknown>;
    if ('$value' in record) {
      const name = path.join('.'), cssName = kebab(name);
      if (!name || names.has(cssName)) throw new Error(`Duplicate emitted token ${name}`);
      names.add(cssName); tokens.set(name, record as Token); return;
    }
    for (const [key, child] of Object.entries(record)) {
      if (key.startsWith('$')) continue;
      if (!/^[a-zA-Z0-9_\-]+$/.test(key)) throw new Error(`Invalid token key ${key}`);
      walk(child, [...path, key]);
    }
  }
  walk(input);
  const values: Record<string, string> = {}, visiting = new Set<string>();
  function resolve(name: string): string {
    if (values[name] !== undefined) return values[name]!;
    const token = tokens.get(name);
    if (!token) throw new Error(`Missing token alias ${name}`);
    if (visiting.has(name)) throw new Error(`Token alias cycle at ${name}`);
    visiting.add(name);
    const value = token.$value;
    let out: string;
    const alias = typeof value === 'string' && /^\{([^}]+)\}$/.exec(value);
    if (alias) {
      const target = tokens.get(alias[1]!);
      if (target && target.$type !== token.$type) throw new Error(`Alias type mismatch at ${name}`);
      out = resolve(alias[1]!);
    } else if (token.$type === 'color') {
      const c = value as { colorSpace?: string; components?: number[]; alpha?: number };
      if (!c || c.colorSpace !== 'srgb' || !Array.isArray(c.components) || c.components.length !== 3 || c.components.some((v) => !Number.isFinite(v) || v < 0 || v > 1) || (c.alpha !== undefined && c.alpha !== 1)) throw new Error(`Invalid opaque sRGB colour ${name}`);
      out = `#${c.components.map((v) => Math.round(v * 255).toString(16).padStart(2, '0')).join('').toUpperCase()}`;
    } else if (token.$type === 'dimension' || token.$type === 'duration') {
      const d = value as { value?: number; unit?: string };
      const units = token.$type === 'dimension' ? ['px', 'rem', 'em', 'ch'] : ['ms', 's'];
      if (!d || typeof d.value !== 'number' || !Number.isFinite(d.value) || d.value < 0 || !units.includes(d.unit ?? '')) throw new Error(`Invalid ${token.$type} ${name}`);
      out = `${d.value}${d.unit}`;
    } else if (token.$type === 'number' || token.$type === 'fontWeight') {
      if (typeof value !== 'number' || !Number.isFinite(value) || value < 0 || (token.$type === 'fontWeight' && (value < 1 || value > 1000))) throw new Error(`Invalid number ${name}`);
      out = String(value);
    } else if (token.$type === 'fontFamily' || token.$type === 'string') {
      if (typeof value !== 'string' || !value || /[;{}<>\\\n\r]/.test(value)) throw new Error(`Invalid string ${name}`);
      out = value;
    } else throw new Error(`Unsupported token type ${token.$type} at ${name}`);
    visiting.delete(name); values[name] = out; return out;
  }
  for (const name of [...tokens.keys()].sort()) resolve(name);
  const palettes: Record<string, Record<string, string>> = { light: {}, dark: {} }, brand: Record<string, string> = {};
  const common: string[] = [];
  for (const name of Object.keys(values).sort()) {
    const mode = /^(light|dark)\.(.+)$/.exec(name);
    if (mode) palettes[mode[1]!]![kebab(mode[2]!)] = values[name]!;
    else {
      common.push(`  --mp-${kebab(name)}: ${values[name]};`);
      if (name.startsWith('brand.')) brand[name.slice(6)] = values[name]!;
    }
  }
  if (JSON.stringify(Object.keys(palettes.light!).sort()) !== JSON.stringify(Object.keys(palettes.dark!).sort())) throw new Error('Light and dark palettes must define the same roles');
  const declarations = (mode: string) => Object.entries(palettes[mode]!).map(([k, v]) => `  --mp-${k}: ${v};`).join('\n');
  const css = `/* Generated by npm run design. Edit design/tokens.json. */\n:root {\n${common.join('\n')}\n${declarations('light')}\n  color-scheme: light;\n}\n:root[data-theme="dark"] {\n${declarations('dark')}\n  color-scheme: dark;\n}\n@media (prefers-color-scheme: dark) {\n  :root:not([data-theme]) {\n${declarations('dark')}\n    color-scheme: dark;\n  }\n}\n`;
  return { values, palettes, brand, css };
}

export async function buildDesign(): Promise<Record<string, string>> {
  const compiled = compileTokens(JSON.parse(await readFile(new URL('design/tokens.json', ROOT), 'utf8')));
  const primitives = await readFile(new URL('src/ui/design/primitives.css', ROOT), 'utf8');
  return {
    'src/ui/design/tokens.css': compiled.css,
    'src/ui/design/palettes.js': `// Generated by npm run design.\nconst MP_PALETTES = ${JSON.stringify(compiled.palettes, null, 2)};\n`,
    'src/design/generated.ts': `// Generated by npm run design.\nexport const BRAND = ${JSON.stringify(compiled.brand, null, 2)} as const;\nexport const PALETTES = ${JSON.stringify(compiled.palettes, null, 2)} as const;\nexport const DESIGN_CSS = ${JSON.stringify(compiled.css)};\nexport const PRIMITIVES_CSS = ${JSON.stringify(primitives)};\n`,
  };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  for (const [name, content] of Object.entries(await buildDesign())) {
    const dest = new URL(name, ROOT);
    if (check) {
      if (await readFile(dest, 'utf8').catch(() => '') !== content) throw new Error(`Generated design file drifted: ${name}`);
    } else await writeFile(dest, content);
  }
  console.log(check ? 'design outputs are current' : 'generated design outputs');
}
