import { DESIGN_CSS, PRIMITIVES_CSS } from './design/generated.ts';
/**
 * The public pages: the landing page at /, /privacy, /terms, /support and /security, the screenshots
 * they show (/site/chat-*.png, from scripts/screenshots.ts), the launch video (/site/launch.mp4, made with /brag from those
 * scenes), and the brand files browsers and link previews ask for
 * (favicon, app icon, social card; generated by scripts/brand.ts). No scripts, no
 * third-party requests.
 *
 * The privacy policy describes what this software stores and sends. It applies to
 * whoever runs the server; MCPORTAL_OPERATOR names them on the pages.
 */
import { readFileSync, createReadStream } from 'node:fs';
import { stat } from 'node:fs/promises';
import { pipeline } from 'node:stream/promises';
import type { ServerResponse } from 'node:http';
import { fileURLToPath } from 'node:url';
import { escapeHtml } from './lib/web.ts';

export const DEFAULT_SUPPORT_URL = 'https://github.com/lbliii/mcportal/issues';
const POLICY_UPDATED = '2026-10-03';   // bump when what's stored changes
const TERMS_UPDATED = '2026-10-02';    // bump when the terms change (and announce material changes first)
const IMAGE_DIR = fileURLToPath(new URL('./site/', import.meta.url));
const TAGLINE = 'Your liminal webspace.';
/** The hero's night sky, drawn by scripts/brand.ts with class hooks for the opening below. */
const HERO_ART = readFileSync(new URL('../brand/hero.svg', import.meta.url), 'utf8').trim();
const DESCRIPTION = 'MCPortal is a reading room that lives in your agent: the sites, feeds, channels, repos and docs you follow, one door away.';

/** Every file served from src/site, by URL path. Nothing else in that folder is reachable. */
const FILES: Record<string, { file: string; type: string; maxAge: number }> = {
  '/site/chat-room.png': { file: 'chat-room.png', type: 'image/png', maxAge: 86_400 },
  '/site/chat-reader.png': { file: 'chat-reader.png', type: 'image/png', maxAge: 86_400 },
  '/site/chat-docs.png': { file: 'chat-docs.png', type: 'image/png', maxAge: 86_400 },
  '/site/chat-reblog.png': { file: 'chat-reblog.png', type: 'image/png', maxAge: 86_400 },
  '/site/launch.mp4': { file: 'launch.mp4', type: 'video/mp4', maxAge: 86_400 },
  '/site/launch.jpg': { file: 'launch.jpg', type: 'image/jpeg', maxAge: 86_400 },
  '/site/og.png': { file: 'og.png', type: 'image/png', maxAge: 86_400 },
  '/site/lockup-on-dark.svg': { file: 'lockup-on-dark.svg', type: 'image/svg+xml', maxAge: 86_400 },
  '/site/jost-bold.ttf': { file: 'jost-bold.ttf', type: 'font/ttf', maxAge: 604_800 },
  '/site/icon-512.png': { file: 'icon-512.png', type: 'image/png', maxAge: 86_400 },
  '/favicon.ico': { file: 'favicon.ico', type: 'image/x-icon', maxAge: 86_400 },
  '/favicon.svg': { file: 'favicon.svg', type: 'image/svg+xml', maxAge: 86_400 },
  '/apple-touch-icon.png': { file: 'apple-touch-icon.png', type: 'image/png', maxAge: 86_400 },
};

export interface SiteConfig {
  publicUrl: string;
  /** Where people get help: an issues page or a mailto: link. */
  supportUrl: string;
  /** Who runs this server, e.g. "Jane Doe". Optional. */
  operator?: string;
  /** Where support requests and security reports go. Without it, security reports go to supportUrl. */
  contactEmail?: string;
  /** The law the terms are under, e.g. "the State of Oregon, USA". Optional. */
  jurisdiction?: string;
  /** The public source code. Unset, the pages don't link to it (the repo isn't public yet). */
  sourceUrl?: string;
  /** Sign-up is invite-only (admins or an allowlist are set). */
  inviteOnly: boolean;
}

const HEADERS = {
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'DENY',
  'referrer-policy': 'no-referrer',
  'content-security-policy': "default-src 'none'; style-src 'unsafe-inline'; img-src 'self'; media-src 'self'; font-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'",
};

/**
 * The landing page in motion, all CSS (the pages run no scripts). The headline carries a teal
 * keyline plate a few pixels off register. On load the hero's layers land like printing plates,
 * the orbit draws itself and the door swings open on the moon (the hooks are classes in
 * brand/hero.svg). Below, each screenshot develops out of a coarse halftone as it scrolls in,
 * its colour block sliding out behind it; heading rules print in and step numbers stamp down.
 * Scroll effects run only where the browser has scroll timelines; everywhere else, and with
 * reduced motion, the page is simply in its finished state.
 */
const MOTION_CSS = `
@supports (content:"a"/""){
  .hero h1::after{content:attr(data-text)/"";position:absolute;inset:0;color:transparent;-webkit-text-stroke:1.5px var(--mp-brand-teal);opacity:.7;pointer-events:none;transform:translate(4px,-3px);transition:transform 600ms var(--mp-ease-press)}
  .hero h1:hover::after{transform:translate(9px,-6px)}
}
@media (forced-colors:active){.hero h1::after{display:none}}
@media (prefers-reduced-motion:no-preference){
  .hero h1,.hero .lede,.hero .cta{animation:ink-in var(--mp-duration-register) var(--mp-ease-press) both}
  .hero .lede{animation-delay:120ms}.hero .cta{animation-delay:220ms}
  .hero h1::after{animation:plate-type var(--mp-duration-register) var(--mp-ease-press) 350ms both}
  .hero .planet{animation:plate-planet var(--mp-duration-swing) var(--mp-ease-press) both}
  .hero .door{animation:plate-door var(--mp-duration-register) var(--mp-ease-press) 100ms both}
  .hero .keyline{animation:plate-keyline var(--mp-duration-register) var(--mp-ease-press) 500ms both}
  .hero .orbit{stroke-dasharray:1 1;animation:draw var(--mp-duration-swing) var(--mp-ease-swing) 300ms both}
  .hero .orbit-front{animation-delay:700ms}
  .hero .leaf{transform-box:fill-box;transform-origin:0 50%;animation:swing-open var(--mp-duration-swing) var(--mp-ease-swing) 900ms both}
  .hero .moon{animation:rise var(--mp-duration-register) var(--mp-ease-press) 1300ms both}
  .hero .stars{animation:twinkle 6s ease-in-out infinite}.hero .stars-2{animation-delay:-2s}.hero .stars-3{animation:twinkle 7.5s ease-in-out -4s infinite}
  @keyframes ink-in{from{opacity:0;transform:translateY(8px)}}
  @keyframes plate-type{from{opacity:0;transform:translate(22px,-16px)}}
  @keyframes plate-planet{from{opacity:0;transform:translate(-16px,10px)}}
  @keyframes plate-door{from{opacity:0;transform:translate(18px,-12px)}}
  @keyframes plate-keyline{from{opacity:0;transform:translate(40px,-28px)}}
  @keyframes draw{from{stroke-dashoffset:1}to{stroke-dashoffset:0}}
  @keyframes swing-open{from{opacity:1;transform:scaleX(1)}to{opacity:1;transform:scaleX(.06)}}
  @keyframes rise{from{opacity:0;transform:translateY(46px)}}
  @keyframes twinkle{50%{opacity:.4}}
  @supports (animation-timeline:view()){
    /* Whatever figure leads the page is at the fold on arrival, so it's already printed. */
    figure:not(:first-child) .print,figure:not(:first-child) img,figure:not(:first-child) .print::after{animation-timing-function:linear;animation-fill-mode:both;animation-timeline:view();animation-range:entry 0% entry 160px}
    figure .print{animation-name:plate-teal}figure.alt .print{animation-name:plate-mustard}figure.alt2 .print{animation-name:plate-brick}
    figure img{animation-name:develop-image}
    figure .print::after{content:"";position:absolute;inset:0;border-radius:calc(var(--mp-radius-card) - 2px);pointer-events:none;opacity:0;background:radial-gradient(circle,var(--mp-brand-ink) 46%,transparent 48%) 0 0/4px 4px;animation-name:develop}
    h2::before{animation:print-rule steps(13,end) both;animation-timeline:view();animation-range:cover 0% cover 12%}
    ol.steps li::before{animation:stamp linear both;animation-timeline:view();animation-range:cover 0% cover 14%}
    @keyframes plate-teal{from{box-shadow:0 0 0 var(--mp-brand-teal)}}
    @keyframes plate-mustard{from{box-shadow:0 0 0 var(--mp-brand-mustard)}}
    @keyframes plate-brick{from{box-shadow:0 0 0 var(--mp-brand-brick)}}
    @keyframes develop{from{opacity:.85;background-size:12px 12px}to{opacity:0;background-size:4px 4px}}
    @keyframes develop-image{from{filter:contrast(1.6) grayscale(.6) brightness(1.05)}to{filter:none}}
    @keyframes print-rule{from{clip-path:inset(0 100% 0 0)}to{clip-path:inset(0)}}
    @keyframes stamp{0%{transform:scale(1.5) rotate(-12deg)}60%{transform:scale(.94)}100%{transform:none}}
  }
}
`;

/**
 * The house style: a mid-century paperback. A night-sky band on top (dark in both schemes),
 * cream paper below (ink in dark mode), Jost for headings, halftone rules, and pictures
 * printed with an off-register block of colour behind them. Colours are brand/README.md's.
 */
const STYLE = `
@font-face{font-family:"MCPortal Jost";src:url(/site/jost-bold.ttf) format("truetype");font-weight:700;font-display:swap}
${DESIGN_CSS}
:root,:root[data-theme],:root:not([data-theme]){--mp-surface-canvas:var(--mp-web-canvas);--mp-surface-card:var(--mp-web-card);--mp-text-primary:var(--mp-web-text);--mp-text-secondary:var(--mp-web-secondary);--mp-text-link:var(--mp-web-link)}
*{box-sizing:border-box}
body{margin:0;background:var(--mp-surface-canvas);color:var(--mp-text-primary);font:1.0625rem/var(--mp-reader-line) var(--mp-font-ui)}
a{color:var(--mp-text-link)}
h1,h2,h3,.jost{font-family:var(--mp-font-heading);font-weight:700;letter-spacing:-.005em}
h1{font-size:clamp(36px,5.2vw,54px);line-height:1.05;margin:0 0 16px}
h2{font-size:30px;line-height:1.15;margin:64px 0 14px}
h2::before{content:"";display:block;width:104px;height:10px;margin-bottom:20px;background:radial-gradient(circle,var(--mp-brand-teal) 1.5px,transparent 1.9px) 0 0/8px 8px}
h3{font-size:var(--mp-type-19);margin:28px 0 4px}
.wrap{max-width:1080px;margin:0 auto;padding:0 24px}
main.wrap{max-width:780px;padding-bottom:72px}
.sky{background:var(--mp-web-night);color:var(--mp-brand-paper);position:relative;overflow:hidden}
.sky a{color:var(--mp-brand-mustard)}
nav{position:relative;z-index:1;display:flex;align-items:center;gap:22px;padding-top:22px;padding-bottom:22px;font-size:var(--mp-type-15)}
nav a.to{color:#D4C8AF;text-decoration:none}nav a.to:hover{color:var(--mp-brand-paper)}
nav .brand{margin-right:auto;display:flex}@media (max-width:520px){nav{gap:18px}}nav .brand img{height:30px;width:auto;display:block}
.sky .title{max-width:780px;position:relative;padding-top:24px;padding-bottom:56px}
.sky .title h1{margin:0}
.hero .art{display:block;width:100%;height:320px}
.hero .pitch{position:relative;z-index:1;padding-top:24px;padding-bottom:40px}
.hero h1{position:relative;font-size:clamp(44px,7vw,76px);line-height:1}
.hero h1 span{color:var(--mp-brand-mustard)}
.hero .lede{font-size:var(--mp-type-19);color:#DDD1B9;max-width:520px;margin:0 0 26px}
.cta{display:flex;flex-wrap:wrap;align-items:center;gap:22px;font-size:16px}
.sky .button{display:inline-block;background:var(--mp-brand-mustard);color:var(--mp-brand-ink);font-weight:600;text-decoration:none;padding:10px 20px;border-radius:var(--mp-radius-control);box-shadow:4px 4px 0 var(--mp-brand-brick)}
@media (min-width:1100px){
  .hero{min-height:560px}
  .hero .art{position:absolute;right:0;bottom:0;width:auto;height:100%}
  .hero .pitch{padding-top:72px;padding-bottom:96px}
  .hero .pitch>*{max-width:40%}
}
.lede{font-size:var(--mp-type-19)}.muted{color:var(--mp-text-secondary);font-size:var(--mp-type-15)}
code{background:var(--mp-surface-inset);padding:1px 6px;border-radius:4px;word-break:break-all;font-size:var(--mp-type-15)}
figure{margin:40px 0}
figure .print{display:block;position:relative;border:2px solid var(--mp-web-frame);border-radius:var(--mp-radius-card);box-shadow:9px 9px 0 var(--mp-brand-teal)}
figure img{display:block;width:100%;height:auto;border-radius:calc(var(--mp-radius-card) - 2px)}
figure.alt .print{box-shadow:9px 9px 0 var(--mp-brand-mustard)}figure.alt2 .print{box-shadow:9px 9px 0 var(--mp-brand-brick)}
figure video{display:block;width:100%;height:auto;border:2px solid var(--mp-web-frame);border-radius:var(--mp-radius-card);box-shadow:9px 9px 0 var(--mp-brand-teal)}
figure.alt video{box-shadow:9px 9px 0 var(--mp-brand-mustard)}
figcaption{color:var(--mp-text-secondary);font-size:var(--mp-type-15);margin-top:16px}
ol.steps{list-style:none;padding:0;margin:24px 0;counter-reset:step}
ol.steps li{counter-increment:step;position:relative;padding-left:58px;margin:0 0 22px;min-height:40px}
ol.steps li::before{content:counter(step);position:absolute;left:0;top:2px;width:38px;height:38px;border-radius:50%;background:var(--mp-brand-mustard);color:var(--mp-brand-ink);display:flex;align-items:center;justify-content:center;font:700 19px/1 "MCPortal Jost",Jost,Futura,sans-serif}
ol.steps b{font-family:"MCPortal Jost",Jost,Futura,sans-serif;font-size:var(--mp-type-19);display:block}
.card{background:var(--mp-surface-card);border:2px solid var(--mp-text-primary);border-radius:var(--mp-radius-lg);padding:20px 24px;margin:28px 0;box-shadow:9px 9px 0 var(--mp-brand-mustard)}
.card p{margin:0}.card p+p{margin-top:10px}
table{border-collapse:collapse;font-size:var(--mp-type-15)}td,th{border-bottom:1px solid var(--mp-web-divider);padding:8px 14px 8px 0;text-align:left;vertical-align:top}
th{font-family:"MCPortal Jost",Jost,Futura,sans-serif}
footer{background:var(--mp-web-night);color:#D4C8AF;font-size:var(--mp-type-15)}
footer .wrap{display:flex;flex-wrap:wrap;align-items:center;gap:8px 24px;padding-top:28px;padding-bottom:28px}
footer .tag{margin-right:auto;color:var(--mp-brand-paper);font-size:17px}
footer a{color:var(--mp-brand-paper)}
${MOTION_CSS}
${PRIMITIVES_CSS}
body{background:var(--mp-web-canvas);color:var(--mp-web-text);line-height:var(--mp-reader-line)}
`;

/**
 * A page: the night-sky band (nav, then `head`), the body on paper, and the footer.
 * `head` is the band's content below the nav; `hero` marks the landing page's taller band with art.
 */
function layout(title: string, head: string, body: string, site: SiteConfig, hero = false): string {
  const by = site.operator ? `<span>Run by ${escapeHtml(site.operator)}</span>` : '';
  const card = escapeHtml(`${site.publicUrl}/site/og.png`);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(title)}</title><meta name="description" content="${escapeHtml(DESCRIPTION)}">
<link rel="icon" href="/favicon.ico" sizes="48x48"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="preload" href="/site/jost-bold.ttf" as="font" type="font/ttf" crossorigin>
<meta property="og:site_name" content="MCPortal"><meta property="og:title" content="${escapeHtml(title)}"><meta property="og:description" content="${escapeHtml(DESCRIPTION)}">
<meta property="og:image" content="${card}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="MCPortal: ${escapeHtml(TAGLINE)}">
<meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#1F2A36">
<style>${STYLE}</style></head><body>
<header class="sky${hero ? ' hero' : ''}">
<nav class="wrap"><a class="brand" href="/"><picture><source media="(max-width:520px)" srcset="/favicon.svg" width="30" height="30"><img src="/site/lockup-on-dark.svg" alt="MCPortal" width="148" height="30"></picture></a><a class="to" href="/privacy">Privacy</a><a class="to" href="/support">Support</a><a class="to" href="/account">Account</a></nav>
${head}${hero ? `\n${HERO_ART}` : ''}
</header>
<main class="wrap">${body}</main>
<footer><div class="wrap"><span class="tag jost">${TAGLINE}</span>${by}<a href="/terms">Terms</a><a href="/privacy">Privacy</a><a href="/security">Security</a><a href="/support">Support</a>${site.sourceUrl ? `<a href="${escapeHtml(site.sourceUrl)}">Source</a>` : ''}</div></footer>
</body></html>`;
}

/** The band's content on pages other than the landing page: just the title. */
const titleBand = (h1: string) => `<div class="wrap title"><h1>${h1}</h1></div>`;

function landing(site: SiteConfig): string {
  const mcp = escapeHtml(`${site.publicUrl}/mcp`);
  const access = site.inviteOnly
    ? `<p><b>MCPortal is in an invite-only beta.</b> If someone sent you an invite link, open it for your setup steps. To ask for an invite, <a href="${escapeHtml(site.supportUrl)}">get in touch</a>.</p>`
    : '<p>Anyone with a GitHub account can sign in.</p>';
  return layout(`MCPortal: ${TAGLINE}`, `
<div class="wrap pitch">
<h1 data-text="Your liminal webspace.">Your liminal <span>webspace.</span></h1>
<p class="lede">A door between your agent and everything you read. Ask for the sites, feeds, subreddits, channels, repos and docs you follow, and they open right in the chat, where you can read them, save them and talk about them.</p>
<p class="cta"><a class="button" href="#get-it">Get it</a><a href="#how">How it works</a></p>
</div>`, `
<figure class="alt"><video src="/site/launch.mp4" poster="/site/launch.jpg" controls playsinline preload="none" width="1600" height="900" aria-label="A 22-second tour of MCPortal: a door opens in a chat onto a reading room; GitHub moves to the left on request; the uv docs open from the repo; a line from a post is clipped; a post is reblogged."></video><figcaption>MCPortal in 22 seconds, with sound.</figcaption></figure>

<figure><span class="print"><img src="/site/chat-room.png" alt="A chat. The person asks for developer news with GitHub on the left and Julia Evans's blog next to it. The agent calls build_room, find_source, add_portal, arrange_room and open_room, and the room appears in the chat: the GitHub Blog, Julia Evans and Lobsters in columns." width="1600" height="1259"></span><figcaption>You ask in plain words. Your agent builds the room, and it opens in the chat.</figcaption></figure>

<h2 id="how">How it works</h2>
<ol class="steps">
  <li><b>Ask for what you read.</b> “Add Julia Evans's blog and r/LocalLLaMA.” Name a site, or paste a feed, <code>r/subreddit</code>, <code>owner/repo</code>, a docs site, or a YouTube, Bluesky or Mastodon address. MCPortal finds a feed that works and tries it before it adds it.</li>
  <li><b>Arrange it by talking.</b> “Put GitHub on the left.” “Make the blog wider.” “Show it as a river.” Starter packs fill a new room in seconds, and OPML import brings your subscriptions over from another reader.</li>
  <li><b>Read, ask and keep.</b> Stories open in a clean reader view with no ads, and your agent can read them with you. Save links for later. Say “clip that” to keep a quote, a table or part of the conversation, and find it again in any later chat.</li>
</ol>
<figure class="alt2"><span class="print"><img src="/site/chat-reader.png" alt="A chat. The person asks what to take from Julia Evans's post on running SQLite and to clip it. The post is open in the reader view in the chat, and the agent answers: run ANALYZE, and says it clipped the quote." width="1600" height="1323"></span><figcaption>Reader view in the chat: the article, your question, and a clip to keep.</figcaption></figure>

<h2>Read the docs you work with</h2>
<p>Give MCPortal a GitHub repo, a docs site or an <code>llms.txt</code>, and it opens the docs as a book: contents and search on the left, the page beside them. It reads a repo's markdown folder as it is, and uses the site's own index (<code>llms.txt</code>, Sphinx inventories, sitemaps) where there is one. Your agent reads the same pages you do, so you can ask about the page in front of you and get answers from the docs rather than from memory.</p>
<figure><span class="print"><img src="/site/chat-docs.png" alt="A chat. The person asks to open the uv docs and explain workspaces. The agent calls open_docs and read_doc_page, and the uv docs from GitHub open in the chat, contents on the left and Using workspaces on the right. The agent answers from the page." width="1600" height="1395"></span><figcaption>The uv docs, read straight from the repo on GitHub.</figcaption></figure>

<h2>Share what you read</h2>
<p>Sign in and you get a Space: a public page of what you choose to share, with your note on each post. Follow other readers and their posts arrive in your room. Reblog a post with your own note and it stays credited to the person who posted it. When you want more people to follow, your agent can suggest readers who share your sources and topics, and say why.</p>
<figure class="alt"><span class="print"><img src="/site/chat-reblog.png" alt="A chat. The person asks what the people they follow are sharing and to reblog Ana's post with a note. The room shows the river: @ana's shared Hacker News story with her note, now marked Reblogged, then a post by @dee that reblogged @cy." width="1600" height="1363"></span><figcaption>The river: your feeds and the people you follow, in one stream.</figcaption></figure>

<h2>Private by design</h2>
<p>MCPortal fetches feeds and pictures on its server, so the sites you read don't see you until you open the original. There are no ads, trackers or analytics. Sign-in is through GitHub, and from GitHub MCPortal keeps only your user ID and login. Your layout, sources, saved items and clips are yours: export them any time in open formats, or delete your account yourself. Details are in the <a href="/privacy">privacy policy</a>.</p>

<h2 id="get-it">Get it</h2>
${access}
<div class="card"><p>Add MCPortal to your agent as a custom connector (MCP server) with this URL, and sign in with GitHub. Then ask <i>“open my room”</i>.</p><p><code>${mcp}</code></p><p class="muted">In Claude, that's <b>Settings → Connectors</b>. MCPortal works in any MCP agent; the visual room appears in agents that show MCP Apps, and elsewhere you read through the chat.</p></div>
<p class="muted">Prefer to run it yourself? MCPortal also runs locally as a Claude Code plugin with no account.${site.sourceUrl ? ` See the <a href="${escapeHtml(site.sourceUrl)}">source</a>.` : ''}</p>`, site, true);
}

function privacy(site: SiteConfig): string {
  const who = site.operator ? escapeHtml(site.operator) : 'the person who runs this server';
  const support = escapeHtml(site.supportUrl);
  return layout('MCPortal privacy policy', titleBand('Privacy policy'), `
<p class="muted" style="margin-top:40px">Last updated ${POLICY_UPDATED}. This policy covers the MCPortal service at <code>${escapeHtml(site.publicUrl)}</code>, which is run by ${who}.</p>

<p>Here's the short version. MCPortal stores your GitHub user ID and login, your room (layout, sources, saved items and clips), what you've read in it, a public profile, shares and follows only if you use them, and sign-in tokens. It doesn't store your email, your name or your GitHub password. It has no ads, trackers or analytics, and it doesn't sell or share your data.</p>

<h2>What MCPortal stores</h2>
<table>
<tr><th>Data</th><th>Why</th><th>How long</th></tr>
<tr><td><b>Account:</b> your GitHub numeric user ID and login, your role, how you joined (for example, by invite), and dates</td><td>To know who you are and whether you're allowed in</td><td>Until your account is deleted</td></tr>
<tr><td><b>Your room:</b> its name, layout, the sources you add (feed addresses, subreddits, repos, searches), and settings</td><td>To show you your room</td><td>Until you change it or your account is deleted</td></tr>
<tr><td><b>People suggestions:</b> the people your agent suggested following, with the one-line reason it wrote, and the ones you said "Not for me" to</td><td>For your People portal, and so your agent knows whom you passed on</td><td>30 days for a suggestion, 90 for a pass. Only you see them; the people suggested never do</td></tr>
<tr><td><b>Saved items:</b> the link, title, source, date and any note you add</td><td>To show your Saved portal</td><td>Until you remove them</td></tr>
<tr><td><b>Clips:</b> quotes, parts of a conversation, notes, tables, images and links you ask your agent to keep, with any title, note and tags</td><td>To show your Clips portal and find them again in later chats</td><td>Until you delete them</td></tr>
<tr><td><b>Reading history:</b> the links you've seen, opened or read in your room, with their titles, when, and how far you got</td><td>To mark what's new and pick up where you left off</td><td>The latest 1,000 per account, until your account is deleted</td></tr>
<tr><td><b>Seen marks:</b> which items in each portal you've already seen, stored as short one-way hashes of the items' ids</td><td>To mark what's new in each portal</td><td>Until you remove the portal or your account is deleted</td></tr>
<tr><td><b>Highlights:</b> the picks your agent makes for the top of your room, in its own words</td><td>To lead your room with them</td><td>24 hours, until replaced; expired ones are removed within a day</td></tr>
<tr><td><b>Pages sent to a new chat:</b> the link, title and any passage you selected when you send a page from the reader to a new chat</td><td>To open it there</td><td>7 days, at most 50; expired ones are removed within a day</td></tr>
<tr><td><b>Pinned results:</b> if you ask your agent to pin results from another connected tool (for example, a list of issues), the titles, links, short summaries and details it copies in, and the request needed to refresh them</td><td>To show that portal</td><td>Until you remove the portal</td></tr>
<tr><td><b>Public profile and space (only if you create one):</b> your handle, display name, bio, space title and colour, and the sources you choose to feature, which other signed-in MCPortal users can see</td><td>So people can find you</td><td>Until you remove it; a handle you give up stays reserved for you for 30 days. If you delete your account, your handles stay reserved for 30 days, so nobody can pose as you, without saying whose they were</td></tr>
<tr><td><b>Shares:</b> links and clips you choose to share, with your note, a copy of what you shared, and who it's for (your followers or everyone on MCPortal)</td><td>To show them to the people you shared them with</td><td>Until you remove them</td></tr>
<tr><td><b>Follows, mutes and blocks:</b> who you follow, mute and block</td><td>To build your Following portal and keep blocked people apart</td><td>Until you change them. People see how many followers you have, never who</td></tr>
<tr><td><b>Listing:</b> whether you chose to be findable by people with similar sources (off unless you turn it on)</td><td>So find_people can suggest you, from your public profile, featured sources and posts shared with everyone, and so those posts (at most 3 a day) appear in the Lobby, and next to the same story in other people's rivers ("also shared by")</td><td>Until you turn it off, which takes you out of suggestions at once</td></tr>
<tr><td><b>Space links:</b> whose Space link you signed in through, and, if it brought a new account, that you joined through it</td><td>So your room offers to follow them once, and they hear once that you joined</td><td>Until your room or theirs has said so (a block removes it at once)</td></tr>
<tr><td><b>Reports:</b> what you reported, why, and when</td><td>So admins can act on abuse</td><td>Deleted 180 days after they're resolved. If you delete your account, reports you made no longer name you (and, once resolved, lose the reason you gave), and reports about you no longer name you</td></tr>
<tr><td><b>Sign-in tokens:</b> stored only as one-way hashes, with the app that asked for them (for example, Claude). An app's registration records the name it gives, which for MCPortal on your own computer includes the computer's name</td><td>To keep you signed in</td><td>Access tokens 1 hour; refresh tokens 30 days. An app registration nobody is signed in with is deleted after 180 days unused, and the ones only you used are deleted with your account</td></tr>
<tr><td><b>Invites and the admin audit log:</b> who invited whom, accounts being created and deleted, and suspensions or reinstatements with a short reason</td><td>To run invites and keep a record of admin actions</td><td>Log entries for a year at most (and only the newest 2,000). Invites nobody used lapse after 90 days. If you delete your account, its entries no longer say whose they were</td></tr>
</table>
<p>Usage counters (for rate limits), admin sessions and sign-in attempts in progress are held in memory only and are gone when the server restarts. Your IP address is used for rate limiting in memory and isn't stored.</p>

<h2>Signing in with GitHub</h2>
<p>MCPortal uses GitHub to read your public user ID and login once, when you sign in. It then discards the GitHub token. MCPortal's sign-in does not read your private repositories or email.</p>

<h2>What MCPortal sends to other sites</h2>
<p>When your room loads, MCPortal's server fetches the feeds, articles and thumbnails you asked for. Those sites see the server's address, not yours. For some large pictures on WordPress sites, the server asks WordPress.com's image service (run by Automattic) for a smaller copy, so that service sees the picture's address too. Fetched content is cached in the server's memory for between two minutes and one day. Some public content is shared across accounts; docs page bodies are cached per account so searches reflect only that account's reads. It isn't written to the database. When you choose to open an original story or its discussion, your browser goes to that site directly, and that site's own privacy policy applies.</p>
<p>What you see in your room is also available to the agent you use it in, and that agent's privacy policy covers your conversations (in Claude, Anthropic's).</p>

<h2>MCPortal on your own computer</h2>
<p>You can also run MCPortal on your own computer (the Claude Code plugin, the desktop bundle, or from source). Until you sign in, it's in ghost mode: everything stays in <code>~/.mcportal</code> on that computer, it fetches feeds and pages itself, and it sends nothing to this service.</p>
<p>If you sign in from it, your room, saved items, clips, reading history, seen marks, public profile, shares and follows are stored by this service exactly as the table above says, and the first sign-in adds that computer's portal to your account. MCPortal on your computer still fetches feeds, articles and pictures itself, so those sites see your computer's address rather than the server's. Its sign-in tokens are kept in a file on your computer that only your user can read. Signing out copies your portal back to the computer, ends that sign-in, and deletes the file. Your <a href="/account">account page</a> lists each signed-in computer by name, and you can revoke one from there, for example if you lose it.</p>

<h2>What other people see</h2>
<p>Nothing, unless you choose. With a public profile, you have a space: signed-in MCPortal users can open it to see your handle, name, bio, space title, the sources you chose to feature, your follower count, and the shares you made for them (your followers, or everyone). Your Space link (<code>/@handle</code>) shows only your handle to people who aren't signed in. Shares are never published to the open web. Admins can see reported shares and profiles, and can hide a share or suspend an account.</p>

<h2>Logs</h2>
<p>Server logs record which tool ran, whether it worked, how long it took, and a reference that lets one server's logs be read together. The reference is a keyed one-way hash of your account that changes every time the server restarts, so it can't be traced back to you. Logs don't record your user ID, your IP address, what you read or what you asked for. An error message can occasionally include the name of a site that failed to load. Separately, the hosting provider (Railway) keeps request logs, which include IP addresses and the pages requested, for a limited time.</p>

<h2>Cookies</h2>
<p>MCPortal uses cookies only to complete a GitHub sign-in (they last 10 minutes), to keep you signed in to your account page (1 hour), and to keep admins signed in to the admin page (8 hours). There are no tracking or advertising cookies.</p>

<h2>Where it's stored</h2>
<p>Data is stored in a Postgres database hosted by Railway in the United States. Only the operator can access it. When scheduled backups are added, this page will say how long they're kept.</p>

<h2>Service providers</h2>
<ul>
  <li><b>Railway:</b> hosts the service and its Postgres database, and processes hosting request logs.</li>
  <li><b>GitHub:</b> completes your sign-in and supplies your public user ID and login.</li>
  <li><b>Automattic (WordPress.com):</b> its image service receives the address of some large WordPress pictures when MCPortal asks for a smaller copy.</li>
</ul>

<h2>Your choices</h2>
<ul>
  <li><b>See and change your data:</b> ask your agent to show your room's settings, change them, or remove saved items at any time.</li>
  <li><b>Take it with you:</b> ask your agent to export your data, or download it from your <a href="/account">account page</a>: everything as one file another MCPortal can import, saved items as a bookmarks file, clips as Markdown, and sources as OPML.</li>
  <li><b>Delete clips, shares or your public profile, or block someone:</b> ask your agent at any time. Removing your public profile hides your shares from everyone.</li>
  <li><b>Delete your account:</b> sign in on your <a href="/account">account page</a> and delete it. Your account, room, saved items, clips, public profile, shares and follows are deleted at once, and you're signed out everywhere. What outlasts it names nobody: reports, the audit log's record that an account was deleted, and your handles, reserved for 30 days so nobody can pose as you. If you can't sign in any more (for example, you lost access to GitHub), ask through support and the operator can delete it for you.</li>
  <li><b>Disconnect:</b> remove MCPortal from your agent's connectors, sign out from MCPortal on your computer, or revoke a computer or app on your <a href="/account">account page</a>. You can also revoke it on GitHub under Settings → Applications.</li>
</ul>

<h2>Children</h2>
<p>MCPortal isn't meant for anyone under 13, or under the minimum age for a GitHub account where you live.</p>

<h2>Changes</h2>
<p>If this policy changes, the date at the top changes too. Changes that affect what's stored or who can see it will be announced on this page before they take effect.</p>
<ul>
  <li><b>3 October 2026:</b> names the service providers together and clarifies the public GitHub data used at sign-in.</li>
  <li><b>2 October 2026:</b> describes reading state, seen marks, highlights, handoffs, linked computers, deletion and scheduled retention; clarifies that backup retention is not yet verified.</li>
</ul>

<h2>Contact</h2>
<p>Questions or requests: <a href="${support}">${support}</a>.</p>`, site);
}

/** How to reach the operator: the contact address, else the support link. */
function contactLink(site: SiteConfig): string {
  if (site.contactEmail) {
    const email = escapeHtml(site.contactEmail);
    return `<a href="mailto:${email}">${email}</a>`;
  }
  const url = escapeHtml(site.supportUrl);
  return `<a href="${url}">${url}</a>`;
}

function terms(site: SiteConfig): string {
  const who = site.operator ? escapeHtml(site.operator) : 'the person who runs this server';
  const law = site.jurisdiction
    ? `<p>These terms are governed by the laws of ${escapeHtml(site.jurisdiction)}, without regard to its conflict-of-law rules. If you're a consumer, you keep any protections the law where you live gives you that can't be waived.</p>`
    : `<p>Where the law of a particular place applies, you keep any protections the law where you live gives you that can't be waived.</p>`;
  return layout('MCPortal terms of service', titleBand('Terms of service'), `
<p class="muted" style="margin-top:40px">Last updated ${TERMS_UPDATED}. These terms cover the MCPortal service at <code>${escapeHtml(site.publicUrl)}</code>, which is run by ${who} ("we"). The <a href="/privacy">privacy policy</a> says what's stored and for how long.</p>

<p>Here's the short version. Use MCPortal to read, keep and share things you have the right to share. Don't use it to hurt people, break the law, or attack MCPortal or the sites it reads. You own what you put in; you can take it with you or delete it any time. MCPortal is provided as is, by a small operator, without guarantees.</p>

<h2>Your account</h2>
<ul>
  <li>You sign in with a GitHub account. You need to be at least 13, and old enough to have a GitHub account where you live.</li>
  <li>An account is for one person. Keep your GitHub account secure: what's done with your MCPortal account is your responsibility, including what your agent does in it on your behalf.</li>
  <li>Using MCPortal on your own computer without signing in (ghost mode) doesn't involve the service at all; these terms cover the hosted service.</li>
</ul>

<h2>What MCPortal does</h2>
<p>MCPortal fetches feeds, pages and pictures from the public web when you ask for them, and shows them in your agent. That content belongs to the sites that publish it, and their terms apply to it. We don't control or check it, and it can be wrong, gone, or not what you expected. Your agent (for example, Claude) is a separate service with its own terms.</p>

<h2>Your content</h2>
<ul>
  <li>What you put in MCPortal (your room, saved items, notes, clips, profile and shares) stays yours. You give us permission to store it, process it and show it to the people you choose, only as needed to run MCPortal for you. That permission ends when you delete it, except for copies kept for the times the privacy policy states.</li>
  <li>Shares and your public profile are seen by the audience you pick (your followers, or everyone signed in to MCPortal). Only share what you have the right to share, and remember that people who can see something can copy it.</li>
  <li>You can export everything in open formats, or delete your account yourself, at any time.</li>
</ul>

<h2>Acceptable use</h2>
<p>Don't use MCPortal, in what you share or how you use the service, to:</p>
<ul>
  <li>break the law, or help someone else do so;</li>
  <li>harass, threaten or bully anyone, or promote violence or hatred against people for who they are;</li>
  <li>share sexual content involving minors (we report it), sexually explicit material, or content that sexualizes anyone without their consent;</li>
  <li>share someone's private information without their permission;</li>
  <li>impersonate someone, or mislead people about who you are;</li>
  <li>spam, or share malware, phishing or deceptive links;</li>
  <li>infringe someone else's copyright, trademark or other rights;</li>
  <li>get around usage limits, blocks or suspensions, or use more than one account to do so;</li>
  <li>probe, overload or break into MCPortal or other people's accounts, or use MCPortal to send abusive or excessive traffic to other sites. (Security research that follows the <a href="/security">security page</a> is welcome.)</li>
</ul>

<h2>Reports, moderation and limits</h2>
<p>Anyone can report a share or a profile. Admins review reports and may hide a share, remove a profile, or suspend an account that breaks these terms; we try to say why, and you can ask us to look again at ${contactLink(site)}. Usage limits keep the service fair and affordable; when you reach one, MCPortal says what it is and when it resets.</p>

<h2>Changes and availability</h2>
<p>MCPortal is a young service. It can change, gain or lose features, have downtime, or lose data despite our care, so keep your own export of anything you can't do without. If we ever shut the hosted service down, we'll give at least 30 days' notice, so you can export your data.</p>
<p>There are no paid features today. If we add any, their price and terms will be shown before you pay, and nothing you use today for free will be taken away to make you pay for it without notice.</p>

<h2>Ending</h2>
<p>You can stop using MCPortal and delete your account any time. We may suspend or close an account that seriously or repeatedly breaks these terms, or to protect people or the service. What happens to your data then is in the privacy policy.</p>

<h2>No warranty</h2>
<p>MCPortal is provided "as is" and "as available", without warranties of any kind, express or implied, including fitness for a particular purpose, to the extent the law allows.</p>

<h2>Limitation of liability</h2>
<p>To the extent the law allows, we aren't liable for indirect, incidental, special or consequential damages, or for lost data, profits or goodwill, arising from your use of MCPortal. Our total liability for any claim about MCPortal is limited to the greater of what you paid us for it in the 12 months before the claim, or 50 US dollars. Nothing here limits liability that the law doesn't allow to be limited.</p>

<h2>Governing law</h2>
${law}

<h2>Changes to these terms</h2>
<p>If these terms change, the date at the top changes too. Changes that affect your rights will be announced on this page at least 14 days before they take effect. Continuing to use MCPortal after that means you accept them; if you don't, you can export your data and delete your account.</p>

<h2>Contact</h2>
<p>Questions about these terms: ${contactLink(site)}.</p>`, site);
}

function support(site: SiteConfig): string {
  return layout('MCPortal support', titleBand('Support'), `
<p class="lede" style="margin-top:40px">Found a bug, need a hand, or want your account deleted? Get in touch at ${contactLink(site)}. We usually reply within a few days. Please don't include tokens or other secrets. Security problems go through the <a href="/security">security page</a>.</p>

<h2>Common questions</h2>
<h3>How do I open my room?</h3>
<p>In a chat with MCPortal connected, ask <i>“open my room”</i> (or “open my portal”). The first time, pick a few starter packs or tell your agent what you like to read.</p>
<h3>How do I add a site?</h3>
<p>Ask your agent to add it, or use the <b>+</b> button in your room. Paste a web address, a feed, <code>r/subreddit</code>, <code>owner/repo</code>, or a YouTube, Bluesky or Mastodon address. MCPortal finds a feed that works and shows you a preview.</p>
<h3>A portal says it couldn't load.</h3>
<p>Some sites block requests from cloud servers or stop publishing their feed. Try refreshing the portal. If it keeps failing, ask your agent to find another feed for that site.</p>
<h3>Claude says my organization doesn't allow custom connectors.</h3>
<p>Some work and school accounts block connectors that aren't in Claude's directory. You can run MCPortal on your own computer instead${site.sourceUrl ? ` (see the <a href="${escapeHtml(site.sourceUrl)}#readme">README</a>)` : ''} and sign in from its room, so it's the same portal as everywhere else. Or use a personal Claude account, or ask your admin.</p>
${site.inviteOnly ? `<h3>I got “sign-in isn't allowed for this account”.</h3>
<p>MCPortal is invite-only right now. The invite is tied to one GitHub account, so sign in as the account that was invited.</p>` : ''}
<h3>How do I bring my subscriptions from another reader?</h3>
<p>Export OPML from your old reader and ask your agent to import it. To take your subscriptions elsewhere, ask your agent to export OPML.</p>
<h3>Someone is bothering me.</h3>
<p>Ask your agent to block them: they can't follow you or see your shares, and you won't see theirs. To tell the admins, ask your agent to report the share or the person.</p>
<h3>How do I get my data out?</h3>
<p>Ask your agent to export it, or download it from your <a href="/account">account page</a>. Everything comes as one file another MCPortal can import; saved items also come as a bookmarks file, clips as Markdown and sources as OPML.</p>
<h3>How do I delete my account?</h3>
<p>Sign in on your <a href="/account">account page</a> and delete it there. It happens at once. See the <a href="/privacy">privacy policy</a> for what's deleted. If you can't sign in any more, get in touch and we'll delete it for you.</p>`, site);
}

function security(site: SiteConfig): string {
  return layout('MCPortal security', titleBand('Security'), `
<p class="lede" style="margin-top:40px">MCPortal reads the open web for you and puts what it finds in front of your agent. Both are places someone could try something, so here is what MCPortal does about it.</p>

<h2>Text from the web can't give your agent orders</h2>
<p>Feeds, articles, docs pages, other people's notes: anything MCPortal didn't write reaches your agent marked as third-party text, inside a fence with a random id that the text itself can't close or fake. Your agent is told to report on it and never follow instructions inside it, including text addressed to AI agents. MCPortal's own tests try exactly that with poisoned content.</p>

<h2>Your agent can't quietly rearrange or delete things</h2>
<p>Changing your layout can't remove a portal unless that portal is named as one you asked to remove, and every change is reported back. Deleting your account isn't something your agent can do at all: it happens only on your account page, after you sign in again.</p>

<h2>MCPortal only fetches from the public web</h2>
<p>Every request MCPortal makes is checked when it connects, so a feed or a link can't point it at a private network, the server itself or a cloud provider's internal addresses, even through redirects or tricks with DNS. Requests have time and size limits, and pages are read with parsers built to stay fast on hostile input.</p>

<h2>Sign-in</h2>
<p>You sign in with GitHub, and MCPortal only learns your GitHub user ID and login. Apps like Claude connect through standard OAuth with PKCE, after MCPortal's own consent screen, which is tied to your browser so it can't be approved from another site. Tokens are short-lived, stored only as hashes, and bound to this server. A suspended account is cut off within seconds.</p>

<h2>Your data</h2>
<p>There are no ads, trackers or analytics. You can export everything in open formats or delete your account yourself. See the <a href="/privacy">privacy policy</a> for what's stored and for how long.</p>

<h2>Report a security problem</h2>
<p>If you find a security issue, please tell us privately at ${contactLink(site)}${site.contactEmail ? ' (put "security" in the subject)' : ''} before sharing it anywhere else. Include what you found, how to reproduce it, and what someone could do with it. Don't include real tokens or other people's data.</p>
<ul>
  <li>We'll acknowledge your report within 3 business days and keep you updated until it's fixed.</li>
  <li>Please give us 90 days to fix it before you share it publicly; we'll credit you when it's fixed, if you'd like.</li>
  <li>Test with your own accounts only. Don't access or change other people's data, degrade the service for others, or use social engineering or spam.</li>
  <li>We won't pursue legal action against good-faith research that follows these guidelines.</li>
</ul>
<p class="muted">Machine-readable: <a href="/.well-known/security.txt">/.well-known/security.txt</a>.</p>`, site);
}

/**
 * RFC 9116: where to report a vulnerability. Expires is required and must be under a
 * year away; it's always 180 days from now, since the file is generated per request.
 */
export function securityTxt(site: SiteConfig, now = new Date()): string {
  const expires = new Date(now.getTime() + 180 * 86_400_000).toISOString().replace(/\.\d+Z$/, 'Z');
  return [
    `Contact: ${site.contactEmail ? `mailto:${site.contactEmail}` : site.supportUrl}`,
    `Expires: ${expires}`,
    'Preferred-Languages: en',
    `Canonical: ${site.publicUrl}/.well-known/security.txt`,
    `Policy: ${site.publicUrl}/security`,
    '',
  ].join('\n');
}

/**
 * Serves /, /privacy, /terms, /support, /security, /.well-known/security.txt and the files in FILES. Returns true if it handled the request.
 * Files honour a single `Range: bytes=…` request, which Safari needs before it will play a video.
 */
export async function serveSite(res: ServerResponse, pathname: string, site: SiteConfig, range?: string): Promise<boolean> {
  const pages: Record<string, (s: SiteConfig) => string> = { '/': landing, '/privacy': privacy, '/terms': terms, '/support': support, '/security': security };
  if (pathname === '/.well-known/security.txt') {
    res.writeHead(200, { 'content-type': 'text/plain; charset=utf-8', 'cache-control': 'public, max-age=3600', ...HEADERS });
    res.end(securityTxt(site));
    return true;
  }
  const render = pages[pathname];
  if (render) {
    res.writeHead(200, { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'public, max-age=300', ...HEADERS });
    res.end(render(site));
    return true;
  }
  const asset = Object.hasOwn(FILES, pathname) ? FILES[pathname] : undefined;
  if (asset) {
    // Stream from disk rather than reading the whole file: a video player asks for many small ranges.
    const path = IMAGE_DIR + asset.file;
    const size = await stat(path).then((s) => s.size, () => undefined);
    if (size === undefined) return false;
    const headers = { 'content-type': asset.type, 'cache-control': `public, max-age=${asset.maxAge}`, 'accept-ranges': 'bytes', ...HEADERS };
    const bytes = range === undefined ? undefined : byteRange(range, size);
    if (bytes === null) {
      res.writeHead(416, { ...headers, 'content-range': `bytes */${size}` });
      res.end();
      return true;
    }
    const { start, end } = bytes ?? { start: 0, end: size - 1 };
    res.writeHead(bytes ? 206 : 200, { ...headers, 'content-length': end - start + 1, ...(bytes && { 'content-range': `bytes ${start}-${end}/${size}` }) });
    if (size === 0) { res.end(); return true; }
    await pipeline(createReadStream(path, { start, end }), res).catch(() => res.destroy());
    return true;
  }
  return false;
}

/** One `bytes=start-end`, `bytes=start-` or `bytes=-suffix` range: undefined to ignore it (serve the whole file), null if it can't be satisfied. */
function byteRange(header: string, size: number): { start: number; end: number } | null | undefined {
  const m = /^bytes=(\d*)-(\d*)$/.exec(header.trim());
  if (!m || (!m[1] && !m[2])) return undefined;
  let start: number, end: number;
  if (!m[1]) { start = Math.max(0, size - Number(m[2])); end = size - 1; }
  else { start = Number(m[1]); end = m[2] ? Math.min(Number(m[2]), size - 1) : size - 1; }
  return start > end || start >= size ? null : { start, end };
}
